
package process;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ProcessService", targetNamespace = "http://soap.sde.isde/", wsdlLocation = "http://floating-bayou-33274.herokuapp.com/ws/process?wsdl")
public class ProcessService
    extends Service
{

    private final static URL PROCESSSERVICE_WSDL_LOCATION;
    private final static WebServiceException PROCESSSERVICE_EXCEPTION;
    private final static QName PROCESSSERVICE_QNAME = new QName("http://soap.sde.isde/", "ProcessService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://floating-bayou-33274.herokuapp.com/ws/process?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PROCESSSERVICE_WSDL_LOCATION = url;
        PROCESSSERVICE_EXCEPTION = e;
    }

    public ProcessService() {
        super(__getWsdlLocation(), PROCESSSERVICE_QNAME);
    }

    public ProcessService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PROCESSSERVICE_QNAME, features);
    }

    public ProcessService(URL wsdlLocation) {
        super(wsdlLocation, PROCESSSERVICE_QNAME);
    }

    public ProcessService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PROCESSSERVICE_QNAME, features);
    }

    public ProcessService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProcessService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Process
     */
    @WebEndpoint(name = "ProcessImplPort")
    public Process getProcessImplPort() {
        return super.getPort(new QName("http://soap.sde.isde/", "ProcessImplPort"), Process.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Process
     */
    @WebEndpoint(name = "ProcessImplPort")
    public Process getProcessImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.sde.isde/", "ProcessImplPort"), Process.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PROCESSSERVICE_EXCEPTION!= null) {
            throw PROCESSSERVICE_EXCEPTION;
        }
        return PROCESSSERVICE_WSDL_LOCATION;
    }

}
