
package process;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Process", targetNamespace = "http://soap.sde.isde/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Process {


    /**
     * 
     * @param password
     * @param userName
     * @return
     *     returns process.User
     */
    @WebMethod
    @WebResult(name = "user", targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "http://soap.sde.isde/", className = "process.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://soap.sde.isde/", className = "process.LoginResponse")
    @Action(input = "http://soap.sde.isde/Process/loginRequest", output = "http://soap.sde.isde/Process/loginResponse")
    public User login(
        @WebParam(name = "userName", targetNamespace = "")
        String userName,
        @WebParam(name = "password", targetNamespace = "")
        String password);

    /**
     * 
     * @param userIn
     * @return
     *     returns process.User
     */
    @WebMethod
    @WebResult(name = "user", targetNamespace = "")
    @RequestWrapper(localName = "createUser", targetNamespace = "http://soap.sde.isde/", className = "process.CreateUser")
    @ResponseWrapper(localName = "createUserResponse", targetNamespace = "http://soap.sde.isde/", className = "process.CreateUserResponse")
    @Action(input = "http://soap.sde.isde/Process/createUserRequest", output = "http://soap.sde.isde/Process/createUserResponse")
    public User createUser(
        @WebParam(name = "userIn", targetNamespace = "")
        User userIn);

    /**
     * 
     * @param userIn
     * @return
     *     returns process.User
     */
    @WebMethod
    @WebResult(name = "user", targetNamespace = "")
    @RequestWrapper(localName = "updateUser", targetNamespace = "http://soap.sde.isde/", className = "process.UpdateUser")
    @ResponseWrapper(localName = "updateUserResponse", targetNamespace = "http://soap.sde.isde/", className = "process.UpdateUserResponse")
    @Action(input = "http://soap.sde.isde/Process/updateUserRequest", output = "http://soap.sde.isde/Process/updateUserResponse")
    public User updateUser(
        @WebParam(name = "userIn", targetNamespace = "")
        User userIn);

    /**
     * 
     * @param idUser
     * @return
     *     returns java.util.List<process.HealthMeasure>
     */
    @WebMethod
    @WebResult(name = "healthMeasures", targetNamespace = "")
    @RequestWrapper(localName = "getRecentHealthMeasureByUser", targetNamespace = "http://soap.sde.isde/", className = "process.GetRecentHealthMeasureByUser")
    @ResponseWrapper(localName = "getRecentHealthMeasureByUserResponse", targetNamespace = "http://soap.sde.isde/", className = "process.GetRecentHealthMeasureByUserResponse")
    @Action(input = "http://soap.sde.isde/Process/getRecentHealthMeasureByUserRequest", output = "http://soap.sde.isde/Process/getRecentHealthMeasureByUserResponse")
    public List<HealthMeasure> getRecentHealthMeasureByUser(
        @WebParam(name = "idUser", targetNamespace = "")
        Long idUser);

    /**
     * 
     * @param idUser
     * @param healthMeasureIn
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "healthMeasure", targetNamespace = "")
    @RequestWrapper(localName = "addHealthMeasure", targetNamespace = "http://soap.sde.isde/", className = "process.AddHealthMeasure")
    @ResponseWrapper(localName = "addHealthMeasureResponse", targetNamespace = "http://soap.sde.isde/", className = "process.AddHealthMeasureResponse")
    @Action(input = "http://soap.sde.isde/Process/addHealthMeasureRequest", output = "http://soap.sde.isde/Process/addHealthMeasureResponse")
    public String addHealthMeasure(
        @WebParam(name = "idUser", targetNamespace = "")
        Long idUser,
        @WebParam(name = "healthMeasureIn", targetNamespace = "")
        HealthMeasure healthMeasureIn);

    /**
     * 
     * @param idUser
     * @return
     *     returns java.util.List<process.HealthMeasure>
     */
    @WebMethod
    @WebResult(name = "healthMeasures", targetNamespace = "")
    @RequestWrapper(localName = "getHistoryOfAllHealthMeasureByUser", targetNamespace = "http://soap.sde.isde/", className = "process.GetHistoryOfAllHealthMeasureByUser")
    @ResponseWrapper(localName = "getHistoryOfAllHealthMeasureByUserResponse", targetNamespace = "http://soap.sde.isde/", className = "process.GetHistoryOfAllHealthMeasureByUserResponse")
    @Action(input = "http://soap.sde.isde/Process/getHistoryOfAllHealthMeasureByUserRequest", output = "http://soap.sde.isde/Process/getHistoryOfAllHealthMeasureByUserResponse")
    public List<HealthMeasure> getHistoryOfAllHealthMeasureByUser(
        @WebParam(name = "idUser", targetNamespace = "")
        Long idUser);

    /**
     * 
     * @param calories
     * @param type
     * @return
     *     returns java.util.List<process.Food>
     */
    @WebMethod
    @WebResult(name = "foods", targetNamespace = "")
    @RequestWrapper(localName = "suggestFoodByCaloriesBound", targetNamespace = "http://soap.sde.isde/", className = "process.SuggestFoodByCaloriesBound")
    @ResponseWrapper(localName = "suggestFoodByCaloriesBoundResponse", targetNamespace = "http://soap.sde.isde/", className = "process.SuggestFoodByCaloriesBoundResponse")
    @Action(input = "http://soap.sde.isde/Process/suggestFoodByCaloriesBoundRequest", output = "http://soap.sde.isde/Process/suggestFoodByCaloriesBoundResponse")
    public List<Food> suggestFoodByCaloriesBound(
        @WebParam(name = "type", targetNamespace = "")
        String type,
        @WebParam(name = "calories", targetNamespace = "")
        double calories);

    /**
     * 
     * @param type
     * @return
     *     returns java.util.List<process.Food>
     */
    @WebMethod
    @WebResult(name = "foods", targetNamespace = "")
    @RequestWrapper(localName = "suggestFoodByType", targetNamespace = "http://soap.sde.isde/", className = "process.SuggestFoodByType")
    @ResponseWrapper(localName = "suggestFoodByTypeResponse", targetNamespace = "http://soap.sde.isde/", className = "process.SuggestFoodByTypeResponse")
    @Action(input = "http://soap.sde.isde/Process/suggestFoodByTypeRequest", output = "http://soap.sde.isde/Process/suggestFoodByTypeResponse")
    public List<Food> suggestFoodByType(
        @WebParam(name = "type", targetNamespace = "")
        String type);

    /**
     * 
     * @param idUser
     * @return
     *     returns java.util.List<process.Goal>
     */
    @WebMethod
    @WebResult(name = "goals", targetNamespace = "")
    @RequestWrapper(localName = "toDoGoal", targetNamespace = "http://soap.sde.isde/", className = "process.ToDoGoal")
    @ResponseWrapper(localName = "toDoGoalResponse", targetNamespace = "http://soap.sde.isde/", className = "process.ToDoGoalResponse")
    @Action(input = "http://soap.sde.isde/Process/toDoGoalRequest", output = "http://soap.sde.isde/Process/toDoGoalResponse")
    public List<Goal> toDoGoal(
        @WebParam(name = "idUser", targetNamespace = "")
        long idUser);

    /**
     * 
     * @param idUser
     * @return
     *     returns java.util.List<process.Goal>
     */
    @WebMethod
    @WebResult(name = "goals", targetNamespace = "")
    @RequestWrapper(localName = "getGoalAchieved", targetNamespace = "http://soap.sde.isde/", className = "process.GetGoalAchieved")
    @ResponseWrapper(localName = "getGoalAchievedResponse", targetNamespace = "http://soap.sde.isde/", className = "process.GetGoalAchievedResponse")
    @Action(input = "http://soap.sde.isde/Process/getGoalAchievedRequest", output = "http://soap.sde.isde/Process/getGoalAchievedResponse")
    public List<Goal> getGoalAchieved(
        @WebParam(name = "idUser", targetNamespace = "")
        long idUser);

    /**
     * 
     * @param idUser
     * @return
     *     returns java.util.List<process.Goal>
     */
    @WebMethod
    @WebResult(name = "goals", targetNamespace = "")
    @RequestWrapper(localName = "failGoal", targetNamespace = "http://soap.sde.isde/", className = "process.FailGoal")
    @ResponseWrapper(localName = "failGoalResponse", targetNamespace = "http://soap.sde.isde/", className = "process.FailGoalResponse")
    @Action(input = "http://soap.sde.isde/Process/failGoalRequest", output = "http://soap.sde.isde/Process/failGoalResponse")
    public List<Goal> failGoal(
        @WebParam(name = "idUser", targetNamespace = "")
        long idUser);

    /**
     * 
     * @param idUser
     * @param goalIn
     * @return
     *     returns process.Goal
     */
    @WebMethod
    @WebResult(name = "goal", targetNamespace = "")
    @RequestWrapper(localName = "followGoal", targetNamespace = "http://soap.sde.isde/", className = "process.FollowGoal")
    @ResponseWrapper(localName = "followGoalResponse", targetNamespace = "http://soap.sde.isde/", className = "process.FollowGoalResponse")
    @Action(input = "http://soap.sde.isde/Process/followGoalRequest", output = "http://soap.sde.isde/Process/followGoalResponse")
    public Goal followGoal(
        @WebParam(name = "idUser", targetNamespace = "")
        long idUser,
        @WebParam(name = "goalIn", targetNamespace = "")
        Goal goalIn);

    /**
     * 
     * @param idUser
     * @return
     *     returns java.util.List<process.Activity>
     */
    @WebMethod
    @WebResult(name = "activities", targetNamespace = "")
    @RequestWrapper(localName = "getMyDoneActivity", targetNamespace = "http://soap.sde.isde/", className = "process.GetMyDoneActivity")
    @ResponseWrapper(localName = "getMyDoneActivityResponse", targetNamespace = "http://soap.sde.isde/", className = "process.GetMyDoneActivityResponse")
    @Action(input = "http://soap.sde.isde/Process/getMyDoneActivityRequest", output = "http://soap.sde.isde/Process/getMyDoneActivityResponse")
    public List<Activity> getMyDoneActivity(
        @WebParam(name = "idUser", targetNamespace = "")
        long idUser);

    /**
     * 
     * @param idUser
     * @param activityIn
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addMyActivity", targetNamespace = "http://soap.sde.isde/", className = "process.AddMyActivity")
    @ResponseWrapper(localName = "addMyActivityResponse", targetNamespace = "http://soap.sde.isde/", className = "process.AddMyActivityResponse")
    @Action(input = "http://soap.sde.isde/Process/addMyActivityRequest", output = "http://soap.sde.isde/Process/addMyActivityResponse")
    public String addMyActivity(
        @WebParam(name = "activityIn", targetNamespace = "")
        Activity activityIn,
        @WebParam(name = "idUser", targetNamespace = "")
        long idUser);

    /**
     * 
     * @param idUser
     * @param healthMeasureType
     * @return
     *     returns process.Activity
     */
    @WebMethod
    @WebResult(name = "activity", targetNamespace = "")
    @RequestWrapper(localName = "getRelatedActivityToHealthType", targetNamespace = "http://soap.sde.isde/", className = "process.GetRelatedActivityToHealthType")
    @ResponseWrapper(localName = "getRelatedActivityToHealthTypeResponse", targetNamespace = "http://soap.sde.isde/", className = "process.GetRelatedActivityToHealthTypeResponse")
    @Action(input = "http://soap.sde.isde/Process/getRelatedActivityToHealthTypeRequest", output = "http://soap.sde.isde/Process/getRelatedActivityToHealthTypeResponse")
    public Activity getRelatedActivityToHealthType(
        @WebParam(name = "healthMeasureType", targetNamespace = "")
        String healthMeasureType,
        @WebParam(name = "idUser", targetNamespace = "")
        long idUser);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "quote", targetNamespace = "")
    @RequestWrapper(localName = "getQuote", targetNamespace = "http://soap.sde.isde/", className = "process.GetQuote")
    @ResponseWrapper(localName = "getQuoteResponse", targetNamespace = "http://soap.sde.isde/", className = "process.GetQuoteResponse")
    @Action(input = "http://soap.sde.isde/Process/getQuoteRequest", output = "http://soap.sde.isde/Process/getQuoteResponse")
    public String getQuote();

}
